export const SENTENCES = [
  "It's two oh nine in the afternoon.",
  "Right now it's overcast in Chapel Hill, sixty-three degrees, with the wind at eleven miles an hour.",
  "Tomorrow looks drizzly, with a high of sixty-four and a low of sixty.",
  "Your timer for the kettle is set for two minutes.",
  "I've set a daily reminder for you to take your medicine at eight in the morning.",
  "You have three reminders: the dentist at three, homework on weekdays at four thirty, and your medicine every morning.",
  "I've put on Steely Dan.",
  "It's paused right now. The song is Butterfly Effect by Travis Scott.",
  "According to WRAL, the town council approved the new bus routes on Tuesday.",
  "The fall semester at Chapel Hill starts on Monday, August seventeenth.",
  "I can't see your PC's screen from your phone. That only works when you're at the PC.",
  "Let me look that up.",
  "One moment.",
  "Welcome back.",
  "Harriet Tubman led about seventy enslaved people to freedom and later served as a scout for the Union Army.",
  "The Nasdaq is at eighteen thousand four hundred and twelve, up about half a percent today.",
  "Got it. I'll remember that your car is a blue Subaru Outback.",
  "I've cleared our conversation history.",
  "Sure. Why did the programmer quit his job? Because he didn't get arrays.",
  "I'm doing well, thanks for asking. What can I help you with?",
  "The air quality is good today, with an index of twenty-nine.",
  "I couldn't find anything about that. Want me to try a different search?",
  "Gaming mode is on. I've freed up the graphics card.",
  "Okay, I'll be a bit more formal from now on.",
];
